FROM {{ source }}:{{ version }}-{{ variant }}

MAINTAINER "{{ maintainer|raw }}"

# Install custom extensions
{% if variant == 'alpine' or variant == 'fpm-alpine' %}
RUN apk upgrade --update && \
    apk add --no-cache sqlite git openssh zip make openssl bash jq && \
    apk add --no-cache --virtual .build-deps libxml2-dev sqlite-dev curl-dev libzip-dev libpng-dev

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
{% else %}
RUN apt-get update && apt-get install -y \
    libsqlite3-dev libzip-dev libpng-dev libgd3 make curl wget bash jq

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
{% endif %}

RUN docker-php-ext-install zip bcmath sockets pdo pdo_mysql gd
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# INSTALL COMPOSER
RUN curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer
RUN alias composer='php /usr/bin/composer'

RUN mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN wget https://get.symfony.com/cli/installer -O - | bash
RUN mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

{% if variant == 'alpine' or variant == 'fpm-alpine' %}
RUN rm -rf /tmp/* /usr/local/lib/php/doc/* /var/cache/apk/*
{% else %}
RUN rm -rf /var/lib/apt/lists/* /tmp/* /usr/local/lib/php/doc/*
{% endif %}
