FROM circleci/php:{{ version }}-fpm-node-browsers

RUN sudo apt-get update && sudo apt-get install -y \
    default-mysql-client software-properties-common python2 libmagickwand-dev --no-install-recommends

RUN sudo docker-php-ext-install pdo_mysql
RUN sudo pecl install imagick \
    && sudo docker-php-ext-enable imagick

RUN sudo ln -sf /usr/share/zoneinfo/Europre/Paris /etc/localtime

RUN sudo mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
COPY sudo symfony.ini $PHP_INI_DIR/conf.d/symfony.ini

RUN curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer

RUN curl -LsS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony/bin/symfony /usr/local/bin/symfony \
    && symfony server:ca:install

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

{% if variant == '15' %}
ENV NODE_VERSION=15.14.0
{% endif %}
ENV NVM_VERSION=0.39.1
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version
RUN npm install --global yarn
RUN yarn --version

# CLEAN
RUN pecl clear-cache \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    /usr/share/doc/* /usr/share/groff/* /usr/share/info/*

RUN mkdir -p /var/www/html
WORKDIR /var/www/html
