name: Build and Push Docker Images

on:
  pull_request:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          # Ansible
          - { path: './ansible/3.15.Dockerfile', tag: 'editionstissot/ansible:3.15-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './ansible/3.16.Dockerfile', tag: 'editionstissot/ansible:3.16-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './ansible/3.17.Dockerfile', tag: 'editionstissot/ansible:3.17-latest', platforms: 'linux/amd64,linux/arm64' }
          # BDESE
          - { path: './bdes/8.3.Dockerfile', tag: 'editionstissot/bdes:8.3-latest', platforms: 'linux/amd64' }
          # OF
          - { path: './of/8.3.Dockerfile', tag: 'editionstissot/of:8.3-latest', platforms: 'linux/amd64,linux/arm64' }
          # PHP
          - { path: './php/8.0.alpine.Dockerfile', tag: 'editionstissot/php:8.0-alpine-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php/8.1.alpine.Dockerfile', tag: 'editionstissot/php:8.1-alpine-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php/8.2.alpine.Dockerfile', tag: 'editionstissot/php:8.2-alpine-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php/8.3.alpine.Dockerfile', tag: 'editionstissot/php:8.3-alpine-latest', platforms: 'linux/amd64,linux/arm64' }
          # PHP - FPM
          - { path: './php/8.0.fpm-alpine.Dockerfile', tag: 'editionstissot/php:8.0-fpm-alpine-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php/8.1.fpm-alpine.Dockerfile', tag: 'editionstissot/php:8.1-fpm-alpine-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php/8.2.fpm-alpine.Dockerfile', tag: 'editionstissot/php:8.2-fpm-alpine-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php/8.3.fpm-alpine.Dockerfile', tag: 'editionstissot/php:8.3-fpm-alpine-latest', platforms: 'linux/amd64,linux/arm64' }
          # PHP
          - { path: './php-node/8.0.playwright.Dockerfile', tag: 'editionstissot/php-node:8.0-playwright-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php-node/8.1.playwright.Dockerfile', tag: 'editionstissot/php-node:8.1-playwright-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php-node/8.2.playwright.Dockerfile', tag: 'editionstissot/php-node:8.2-playwright-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php-node/8.3.playwright.Dockerfile', tag: 'editionstissot/php-node:8.3-playwright-latest', platforms: 'linux/amd64,linux/arm64' }
          # Node
          - { path: './node/16.slim.Dockerfile', tag: 'editionstissot/node:16-slim-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './node/18.slim.Dockerfile', tag: 'editionstissot/node:18-slim-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './node/20.slim.Dockerfile', tag: 'editionstissot/node:20-slim-latest', platforms: 'linux/amd64,linux/arm64' }
          # Node - chrome
          - { path: './node/16.slim-chrome.Dockerfile', tag: 'editionstissot/node:16-slim-chrome-latest', platforms: 'linux/amd64' }
          - { path: './node/18.slim-chrome.Dockerfile', tag: 'editionstissot/node:18-slim-chrome-latest', platforms: 'linux/amd64' }
          - { path: './node/20.slim-chrome.Dockerfile', tag: 'editionstissot/node:20-slim-chrome-latest', platforms: 'linux/amd64' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile.path }}
          push: true
          tags: ${{ matrix.dockerfile.tag }}
          platforms: ${{ matrix.dockerfile.platforms }}
