name: On label image docker

on:
  pull_request:
    types: [ labeled ]

jobs:
  php:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'preview/php' ) }}
    uses: EditionsTissot/docker-image/.github/workflows/image-docker.yaml@main
    with:
      language: php
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  node:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'preview/node' ) }}
    uses: EditionsTissot/docker-image/.github/workflows/image-docker.yaml@main
    with:
      language: node
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  php-node:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'preview/php-node' ) }}
    uses: EditionsTissot/docker-image/.github/workflows/image-docker.yaml@main
    with:
      language: php-node
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  ansible:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'preview/ansible' ) }}
    uses: EditionsTissot/docker-image/.github/workflows/image-docker.yaml@main
    with:
      language: ansible
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  bdes:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'preview/bdes' ) }}
    uses: EditionsTissot/docker-image/.github/workflows/image-docker.yaml@main
    with:
      language: bdes
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  of:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'preview/of' ) }}
    uses: EditionsTissot/docker-image/.github/workflows/image-docker.yaml@main
    with:
      language: of
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
