name: Build & deploy docker image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  php:
    uses: EditionsTissot/docker-image/.github/workflows/image-docker.yaml@main
    with:
      language: php
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  node:
    uses: EditionsTissot/docker-image/.github/workflows/image-docker.yaml@main
    with:
      language: node
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  ansible:
    uses: EditionsTissot/docker-image/.github/workflows/image-docker.yaml@main
    with:
      language: ansible
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  bdes:
    uses: EditionsTissot/docker-image/.github/workflows/image-docker.yaml@main
    with:
      language: bdes
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
